### ISSUE TITLE
How can we generate model files by command

### ISSUE THREAD

**Issue by sariluong** [Saritasa/ClickBlocks#1]
- When we want to use a new table in db, we must create some files in folder _engine/bll, _engine/collection, _engine/dal, _engine/orchestra (at least 4 files).
  It takes time and sometimes we get mistakes.

- Question: How can we generate these files by command?

**Comment by oSadykov** [comment]
Hi, you can use ORM class that contains all needed methods.
To generate new ORM classes generateClasses, to generate new db.xml generateXML. 
The simplest way to do this is use Utility script:
**To generate classes**: http://YOUR_HOSTNAME/Utilities/orm/generate.php?mode=classes
**To generate xml**: http://YOUR_HOSTNAME/Utilities/orm/generate.php?mode=xml
